// Mouse configuration
#define ZMK_MOUSE_DEFAULT_MOVE_VAL 2250
#define ZMK_MOUSE_DEFAULT_SCRL_VAL 100

#define U_MOUSE_MOVE_EXPONENT 2
#define U_MOUSE_MOVE_TIME 650
#define U_MOUSE_MOVE_DELAY 0
#define U_MOUSE_SCROLL_TIME 5000
#define U_MOUSE_SCROLL_DELAY 0
